# Generated by Django 4.1.3 on 2022-11-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noice', '0003_alter_user_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pincode',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pincode'),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='State'),
        ),
    ]
