# Generated by Django 4.1.3 on 2022-11-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noice', '0004_alter_user_city_alter_user_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('idorder', models.AutoField(db_column='idOrder', primary_key=True, serialize=False)),
                ('date_of_order', models.DateTimeField(db_column='Date of order')),
                ('amount', models.IntegerField(db_column='Amount')),
            ],
            options={
                'db_table': 'order details',
                'managed': False,
            },
        ),
    ]
