# Generated by Django 4.1.3 on 2022-11-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noice', '0005_orderdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='AskADoctor',
            fields=[
                ('idask_a_doctor', models.AutoField(db_column='idAsk a Doctor', primary_key=True, serialize=False)),
                ('question', models.CharField(blank=True, db_column='Question', max_length=200, null=True)),
                ('answer', models.TextField(blank=True, db_column='Answer', null=True)),
                ('domain', models.CharField(db_column='Domain', max_length=45)),
                ('user_id', models.IntegerField(db_column='User_id')),
            ],
            options={
                'db_table': 'ask a doctor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('idcategory', models.AutoField(db_column='idCategory', primary_key=True, serialize=False)),
                ('category', models.CharField(db_column='Category', max_length=45)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('iddoctor', models.AutoField(db_column='idDoctor', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=45)),
                ('specialisation', models.CharField(db_column='Specialisation', max_length=45)),
                ('email_id', models.CharField(db_column='Email ID', max_length=45)),
                ('phone_no_field', models.IntegerField(db_column='Phone No.')),
                ('state', models.CharField(db_column='State', max_length=45)),
                ('city', models.CharField(db_column='City', max_length=45)),
                ('pincode', models.IntegerField(db_column='Pincode')),
                ('experience_yrs_field', models.IntegerField(blank=True, db_column='Experience(yrs)', null=True)),
                ('photo', models.CharField(blank=True, db_column='Photo', max_length=2048, null=True)),
            ],
            options={
                'db_table': 'doctor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('idfaq', models.AutoField(db_column='idFAQ', primary_key=True, serialize=False)),
                ('question', models.CharField(db_column='Question', max_length=200)),
                ('answer', models.TextField(db_column='Answer')),
                ('subcategory_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'faq',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HealthArticles',
            fields=[
                ('idhealth_articles', models.AutoField(db_column='idHealth Articles', primary_key=True, serialize=False)),
                ('heading', models.CharField(db_column='Heading', max_length=45)),
                ('photo', models.CharField(blank=True, db_column='Photo', max_length=2048, null=True)),
                ('content', models.TextField(blank=True, db_column='Content', null=True)),
                ('subcategory_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'health articles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('idinventory', models.AutoField(db_column='idInventory', primary_key=True, serialize=False)),
                ('expiry_date', models.DateTimeField(blank=True, db_column='Expiry Date', null=True)),
                ('quantity', models.IntegerField(blank=True, db_column='Quantity', null=True)),
                ('quantity_sold_this_month', models.IntegerField(blank=True, db_column='Quantity Sold this Month', null=True)),
            ],
            options={
                'db_table': 'inventory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('idmanufacturer', models.AutoField(db_column='idManufacturer', primary_key=True, serialize=False)),
                ('company_name', models.CharField(db_column='Company Name', max_length=45)),
                ('email', models.CharField(db_column='Email', max_length=45)),
                ('phone_number', models.IntegerField(db_column='Phone number', unique=True)),
                ('manufacturing_headquarters', models.CharField(blank=True, db_column='Manufacturing Headquarters', max_length=45, null=True)),
            ],
            options={
                'db_table': 'manufacturer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('idorder_details', models.AutoField(db_column='idOrder details', primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('product_id', models.IntegerField(db_column='Product_id')),
            ],
            options={
                'db_table': 'order items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('idpayment_details', models.AutoField(db_column='idPayment Details', primary_key=True, serialize=False)),
                ('status', models.CharField(db_column='Status', max_length=45)),
                ('type_of_payment', models.CharField(blank=True, db_column='Type of payment', max_length=45, null=True)),
                ('time_of_payment', models.DateTimeField(blank=True, db_column='Time of Payment', null=True)),
            ],
            options={
                'db_table': 'payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('idproduct', models.AutoField(db_column='idProduct', primary_key=True, serialize=False)),
                ('product_name', models.CharField(db_column='Product name', max_length=50)),
                ('price', models.IntegerField(db_column='Price')),
                ('number_of_purchases', models.IntegerField(blank=True, db_column='Number of purchases', null=True)),
                ('desciption', models.TextField(blank=True, db_column='Desciption', null=True)),
                ('image', models.CharField(blank=True, db_column='Image', max_length=2048, null=True)),
                ('discount', models.IntegerField(blank=True, db_column='Discount', null=True)),
                ('discounted_price', models.IntegerField(blank=True, db_column='Discounted price', null=True)),
                ('stock', models.IntegerField(db_column='Stock')),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('idrating', models.AutoField(db_column='idRating', primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('product_id', models.IntegerField(db_column='Product_id')),
                ('user_id', models.IntegerField(db_column='User_id')),
            ],
            options={
                'db_table': 'rating',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('idreviews', models.AutoField(db_column='idReviews', primary_key=True, serialize=False)),
                ('reviews', models.TextField(db_column='Reviews')),
                ('user_id', models.IntegerField(db_column='User_id')),
                ('product_id', models.IntegerField(db_column='Product_id')),
            ],
            options={
                'db_table': 'reviews',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id_cart', models.AutoField(db_column='id cart', primary_key=True, serialize=False)),
                ('amount', models.IntegerField(blank=True, db_column='Amount', null=True)),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'shopping cart',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShoppingCartItems',
            fields=[
                ('idshopping_cart_items', models.IntegerField(db_column='idShopping Cart items', primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(blank=True, db_column='Quantity', null=True)),
                ('product_id', models.IntegerField(db_column='Product_id')),
            ],
            options={
                'db_table': 'shopping cart items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('sub_category', models.CharField(db_column='Sub Category', max_length=50)),
                ('id_sub_category', models.AutoField(db_column='id_Sub Category', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'sub category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('idwishlist', models.AutoField(db_column='idWishlist', primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(db_column='User_id')),
            ],
            options={
                'db_table': 'wishlist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WishlistItems',
            fields=[
                ('idwishlist_items', models.AutoField(db_column='idWishlist items', primary_key=True, serialize=False)),
                ('product_id', models.IntegerField(db_column='Product_id')),
            ],
            options={
                'db_table': 'wishlist items',
                'managed': False,
            },
        ),
    ]
