# Generated by Django 4.1.3 on 2022-11-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noice', '0006_askadoctor_category_doctor_faq_healtharticles_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User1',
            fields=[
                ('iduser', models.AutoField(db_column='idUser', primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=250)),
                ('user_email_id', models.CharField(blank=True, db_column='User Email_Id', max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('state', models.CharField(db_column='State', max_length=45)),
                ('city', models.CharField(db_column='City', max_length=45)),
                ('pincode', models.IntegerField(db_column='Pincode')),
                ('phone_number', models.IntegerField(blank=True, db_column='Phone Number', null=True)),
                ('profile_image', models.FileField(upload_to='blog-post-images')),
                ('user_bio', models.TextField(blank=True, db_column='User bio', null=True)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'user1',
                'managed': False,
            },
        ),
    ]
