# Generated by Django 4.1.3 on 2022-11-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noice', '0008_user2'),
    ]

    operations = [
        migrations.CreateModel(
            name='User3',
            fields=[
                ('iduser', models.AutoField(db_column='idUser', primary_key=True, serialize=False)),
                ('auth_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=250)),
                ('user_email_id', models.CharField(blank=True, db_column='User Email_Id', max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('state', models.CharField(blank=True, db_column='State', max_length=45, null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=45, null=True)),
                ('pincode', models.IntegerField(blank=True, db_column='Pincode', null=True)),
                ('phone_number', models.IntegerField(blank=True, db_column='Phone Number', null=True)),
                ('profile_image', models.FileField(blank=True, db_column='Profile Image', null=True, upload_to='blog-post-images')),
                ('user_bio', models.TextField(blank=True, db_column='User bio', null=True)),
                ('first_name', models.CharField(blank=True, max_length=45, null=True)),
                ('last_name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'user3',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='User1',
        ),
        migrations.DeleteModel(
            name='User2',
        ),
    ]
